# ============================================================
#  Azure Full Compliance Assessment (50+ Checks)
#  Generates: AzureFullAssessment_Report.html
#  Run via: irm <raw_github_url>/Full_Assessment.ps1 | iex
# ============================================================

function Get-HtmlTemplate {
    param($Title, $SubName, $Date, $Rows, $Pass, $Fail, $Warn, $Total)
    $score = if ($Total -gt 0) { [math]::Round(($Pass / $Total) * 100) } else { 0 }
    $scoreColor = if ($score -ge 80) { "#00c87a" } elseif ($score -ge 60) { "#ffab40" } else { "#ff4d6d" }
    return @"
<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>Azure Assessment - $Title</title><link rel="icon" type="image/png" href="Screenshot_2026-03-10_201227-removebg-preview.png">
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;background:#0a0e1a;color:#e8eaf0;min-height:100vh;padding:30px}.container{max-width:1200px;margin:0 auto}.header{background:linear-gradient(135deg,#0078D4,#003f73);border-radius:16px;padding:32px 36px;margin-bottom:28px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}.header h1{font-size:1.7rem;font-weight:800}.header p{font-size:0.85rem;opacity:.75;margin-top:6px}.score-circle{width:90px;height:90px;border-radius:50%;background:conic-gradient($scoreColor ${score}%, rgba(255,255,255,0.1) 0);display:flex;align-items:center;justify-content:center;flex-direction:column;position:relative}.score-inner{width:72px;height:72px;border-radius:50%;background:#0d1a2e;display:flex;align-items:center;justify-content:center;flex-direction:column;position:absolute}.score-num{font-size:1.3rem;font-weight:800;color:$scoreColor}.score-label{font-size:0.6rem;color:#8892a4;text-transform:uppercase;letter-spacing:.05em}.summary-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:16px;margin-bottom:28px}.sum-card{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:18px;text-align:center}.sum-card .num{font-size:2rem;font-weight:800;margin-bottom:4px}.sum-card .lbl{font-size:0.75rem;color:#8892a4;text-transform:uppercase;letter-spacing:.06em}.pass .num{color:#00c87a}.fail .num{color:#ff4d6d}.warn .num{color:#ffab40}.total .num{color:#50e6ff}table{width:100%;border-collapse:collapse;background:rgba(255,255,255,0.03);border-radius:12px;overflow:hidden}th{background:rgba(0,120,212,0.35);padding:12px 16px;text-align:left;font-size:0.78rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#b0c4de}td{padding:11px 16px;font-size:0.85rem;border-bottom:1px solid rgba(255,255,255,0.06);vertical-align:top}tr:last-child td{border-bottom:none}tr:hover td{background:rgba(0,120,212,0.07)}.footer{text-align:center;margin-top:30px;font-size:0.8rem;color:#4a5568;padding:16px}</style></head>
<body><div class='container'>
  <div class='header'><div><h1>☁ Azure $Title</h1><p>Subscription: $SubName &nbsp;|&nbsp; Generated: $Date</p></div><div class='score-circle'><div class='score-inner'><span class='score-num'>${score}%</span><span class='score-label'>Score</span></div></div></div>
  <div class='summary-cards'><div class='sum-card total'><div class='num'>$Total</div><div class='lbl'>Total Checks</div></div><div class='sum-card pass'><div class='num'>$Pass</div><div class='lbl'>Passed</div></div><div class='sum-card fail'><div class='num'>$Fail</div><div class='lbl'>Failed</div></div><div class='sum-card warn'><div class='num'>$Warn</div><div class='lbl'>Warnings</div></div></div>
  <table><thead><tr><th>Category</th><th>Check</th><th>Resource</th><th>Status</th><th>Details</th></tr></thead><tbody>$Rows</tbody></table>
  <div class='footer'>Azure Cloud Assessment Report &nbsp;|&nbsp; Generated by PowerShell Automation</div>
</div></body></html>
"@
}

Write-Host "Connecting to Azure..." -ForegroundColor Cyan
Connect-AzAccount -ErrorAction SilentlyContinue | Out-Null
$results = @()
$context = Get-AzContext
if (-not $context) { return }
$subName = $context.Subscription.Name
$subId   = $context.Subscription.Id
$date    = (Get-Date).ToUniversalTime().AddHours(5.5).ToString("yyyy-MM-dd HH:mm")

Write-Host "Running Full Assessment on: $subName ($subId)" -ForegroundColor Yellow

# Add default Context row
$results += [PSCustomObject]@{ Category="Subscription"; Check="Active Context"; Resource=$subName; Status="PASS"; Details="Successfully identified subscription: $subId" }

# ── IAM
Write-Host "[1/6] IAM Checks..." -ForegroundColor Cyan
try {
    # 1. Fetch Authorization Policy
    $authPolicy = Invoke-AzRestMethod -Method GET -Url "https://graph.microsoft.com/v1.0/policies/authorizationPolicy/authorizationPolicy"
    if ($authPolicy.StatusCode -eq 200) {
        $p = $authPolicy.Content | ConvertFrom-Json
        $results += [PSCustomObject]@{ Category="IAM"; Check="Guest Permissions"; Resource="Tenant"; Status=if($p.guestUserRoleAllowedToReadOtherUsers){"FAIL"}else{"PASS"}; Details=if($p.guestUserRoleAllowedToReadOtherUsers){"Guests can read other users."}else{"Guest access restricted."} }
        $results += [PSCustomObject]@{ Category="IAM"; Check="App Registration"; Resource="Tenant"; Status=if($p.allowedToCreateApps){"FAIL"}else{"PASS"}; Details=if($p.allowedToCreateApps){"Users can register apps."}else{"Restricted to admins."} }
    }

    # 2. Privileged MFA (Sampling)
    $privRoles = @("Owner","Global Administrator")
    $roleAssignments = Get-AzRoleAssignment -ErrorAction SilentlyContinue | Where-Object { $privRoles -contains $_.RoleDefinitionName }
    foreach ($role in $roleAssignments) {
        $results += [PSCustomObject]@{ Category="IAM"; Check="Privileged MFA"; Resource=$role.DisplayName; Status="WARN"; Details="Verify MFA for $($role.RoleDefinitionName)" }
    }
} catch { $results += [PSCustomObject]@{ Category="IAM"; Check="IAM Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }
    
    # Password Reset & External Access
    $results += [PSCustomObject]@{ Category="IAM"; Check="Guest Invitations"; Resource="Tenant"; Status="WARN"; Details="Restrict guest & member invitation capabilities" }
    $results += [PSCustomObject]@{ Category="IAM"; Check="Password Reset Policy"; Resource="Tenant"; Status="WARN"; Details="Ensure notify users/admins on reset is enabled" }
} catch { $results += [PSCustomObject]@{ Category="IAM"; Check="IAM Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# ── Storage
Write-Host "[2/6] Storage Checks..." -ForegroundColor Cyan
try {
    $accounts = Get-AzStorageAccount
    foreach ($sa in $accounts) {
        $results += [PSCustomObject]@{ Category="Storage"; Check="HTTPS Only"; Resource=$sa.StorageAccountName; Status=if($sa.EnableHttpsTrafficOnly){"PASS"}else{"FAIL"}; Details=if($sa.EnableHttpsTrafficOnly){"HTTPS enforced"}else{"HTTP allowed"} }
        $results += [PSCustomObject]@{ Category="Storage"; Check="Public Blob Access"; Resource=$sa.StorageAccountName; Status=if($sa.AllowBlobPublicAccess){"FAIL"}else{"PASS"}; Details=if($sa.AllowBlobPublicAccess){"Public access ENABLED"}else{"Disabled"} }
        $results += [PSCustomObject]@{ Category="Storage"; Check="Min TLS"; Resource=$sa.StorageAccountName; Status=if($sa.MinimumTlsVersion -ge "TLS1_2"){"PASS"}else{"FAIL"}; Details="TLS: $($sa.MinimumTlsVersion)" }
    }
} catch { $results += [PSCustomObject]@{ Category="Storage"; Check="Storage Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# ── Network
Write-Host "[3/6] Network Checks..." -ForegroundColor Cyan
try {
    $nsgs = Get-AzNetworkSecurityGroup
    foreach ($nsg in $nsgs) {
        $risky = $nsg.SecurityRules | Where-Object { $_.Access -eq "Allow" -and $_.Direction -eq "Inbound" -and $_.SourceAddressPrefix -in @("*","Internet","0.0.0.0/0") }
        $results += [PSCustomObject]@{ Category="Network"; Check="Open NSG Rules"; Resource=$nsg.Name; Status=if($risky){"FAIL"}else{"PASS"}; Details=if($risky){"$($risky.Count) open inbound rule(s)"}else{"No open inbound rules"} }
    }
    $pips = Get-AzPublicIpAddress
    $results += [PSCustomObject]@{ Category="Network"; Check="Public IPs Count"; Resource="Subscription"; Status=if($pips.Count -gt 5){"WARN"}else{"INFO"}; Details="$($pips.Count) public IP(s) found" }
} catch { $results += [PSCustomObject]@{ Category="Network"; Check="Network Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# ── Compute & Services (VMs, App Service, AKS, etc.)
Write-Host "[4/6] Compute & Services..." -ForegroundColor Cyan
try {
    # VMs & Scale Sets
    $vms = Get-AzVM -ErrorAction SilentlyContinue
    foreach ($vm in $vms) {
        $name = $vm.Name; $rg = $vm.ResourceGroupName
        $enc = Get-AzVMDiskEncryptionStatus -ResourceGroupName $rg -VMName $name -ErrorAction SilentlyContinue
        $results += [PSCustomObject]@{ Category="Compute"; Check="Disk Encryption"; Resource=$name; Status=if($enc.OsVolumeEncrypted -eq "Encrypted"){"PASS"}else{"FAIL"}; Details="OS Disk: $($enc.OsVolumeEncrypted)" }
        $results += [PSCustomObject]@{ Category="Compute"; Check="Managed Identity"; Resource=$name; Status=if($vm.Identity){"PASS"}else{"WARN"}; Details=if($vm.Identity){"Identity: $($vm.Identity.Type)"}else{"No managed identity"} }
        
        # New Detailed Checks
        $results += [PSCustomObject]@{ Category="Compute"; Check="Boot Diagnostics"; Resource=$name; Status=if($vm.DiagnosticsProfile.BootDiagnostics.Enabled){"PASS"}else{"FAIL"}; Details="Status: $($vm.DiagnosticsProfile.BootDiagnostics.Enabled)" }
        $results += [PSCustomObject]@{ Category="Compute"; Check="Admin Username"; Resource=$name; Status=if($vm.OSProfile.AdminUsername -in @("admin","root","azureuser")){"WARN"}else{"PASS"}; Details="User: $($vm.OSProfile.AdminUsername)" }
    }

    $vmssList = Get-AzVmss -ErrorAction SilentlyContinue
    foreach ($vmss in $vmssList) {
        $results += [PSCustomObject]@{ Category="Compute"; Check="VMSS Auto Repair"; Resource=$vmss.Name; Status=if($vmss.VirtualMachineProfile.DiagnosticsProfile){"PASS"}else{"WARN"}; Details="Enabled" }
    }
    
    # App Services
    $webApps = Get-AzWebApp
    foreach ($wa in $webApps) {
        $results += [PSCustomObject]@{ Category="App Service"; Check="HTTPS-Only"; Resource=$wa.Name; Status=if($wa.HttpsOnly){"PASS"}else{"FAIL"}; Details="Redirect: $($wa.HttpsOnly)" }
        $results += [PSCustomObject]@{ Category="App Service"; Check="TLS Latest"; Resource=$wa.Name; Status=if($wa.SiteConfig.MinTlsVersion -ge "1.2"){"PASS"}else{"FAIL"}; Details="Min TLS: $($wa.SiteConfig.MinTlsVersion)" }
    }

    # AKS
    $aksClusters = Get-AzAksCluster
    foreach ($aks in $aksClusters) {
        $results += [PSCustomObject]@{ Category="AKS"; Check="RBAC Enabled"; Resource=$aks.Name; Status=if($aks.EnableRbac){"PASS"}else{"FAIL"}; Details="RBAC: $($aks.EnableRbac)" }
        $results += [PSCustomObject]@{ Category="AKS"; Check="Defender"; Resource=$aks.Name; Status=if($aks.SecurityProfile.Defender.SecurityMonitoring.Enabled){"PASS"}else{"FAIL"}; Details="Defender for AKS: $($aks.SecurityProfile.Defender.SecurityMonitoring.Enabled)" }
    }
} catch { $results += [PSCustomObject]@{ Category="Compute"; Check="Compute Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# ── Defender
Write-Host "[5/6] Defender Checks..." -ForegroundColor Cyan
try {
    $plans = Get-AzSecurityPricing
    foreach ($p in ($plans | Where-Object { $_.Name -in @("VirtualMachines","StorageAccounts","SqlServers","AppServices","KeyVaults") })) {
        $results += [PSCustomObject]@{ Category="Defender"; Check="Plan: $($p.Name)"; Resource=$p.Name; Status=if($p.PricingTier -eq "Standard"){"PASS"}else{"FAIL"}; Details="Tier: $($p.PricingTier)" }
    }
    $contacts = Get-AzSecurityContact
    $results += [PSCustomObject]@{ Category="Defender"; Check="Security Contact"; Resource="Subscription"; Status=if($contacts){"PASS"}else{"FAIL"}; Details=if($contacts){"Contact configured"}else{"No security contact set"} }
} catch { $results += [PSCustomObject]@{ Category="Defender"; Check="Defender Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# ── Key Vault
Write-Host "[6/6] Key Vault Checks..." -ForegroundColor Cyan
try {
    $kvs = Get-AzKeyVault
    foreach ($kv in $kvs) {
        $kvd = Get-AzKeyVault -VaultName $kv.VaultName
        $results += [PSCustomObject]@{ Category="Key Vault"; Check="Soft Delete"; Resource=$kv.VaultName; Status=if($kvd.EnableSoftDelete){"PASS"}else{"FAIL"}; Details=if($kvd.EnableSoftDelete){"Soft delete enabled"}else{"Soft delete DISABLED!"} }
        $results += [PSCustomObject]@{ Category="Key Vault"; Check="Purge Protection"; Resource=$kv.VaultName; Status=if($kvd.EnablePurgeProtection){"PASS"}else{"WARN"}; Details=if($kvd.EnablePurgeProtection){"Purge protection enabled"}else{"Not enabled"} }
        $results += [PSCustomObject]@{ Category="Key Vault"; Check="Public Network Access"; Resource=$kv.VaultName; Status=if($kvd.PublicNetworkAccess -eq "Disabled"){"PASS"}else{"WARN"}; Details="Network Access: $($kvd.PublicNetworkAccess)" }
    }
    if (-not $kvs) { $results += [PSCustomObject]@{ Category="Key Vault"; Check="Key Vaults"; Resource="Subscription"; Status="INFO"; Details="No Key Vaults found" } }
} catch { $results += [PSCustomObject]@{ Category="Key Vault"; Check="Key Vault Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

Write-Host "Generating HTML report..." -ForegroundColor Cyan
$rows = ""
foreach ($r in $results) {
    $color = switch ($r.Status) { "PASS"{"#00c87a"} "FAIL"{"#ff4d6d"} "WARN"{"#ffab40"} "INFO"{"#50e6ff"} default{"#8892a4"} }
    $icon  = switch ($r.Status) { "PASS"{"✔"} "FAIL"{"✘"} "WARN"{"⚠"} default{"ℹ"} }
    $rows += "<tr><td>$($r.Category)</td><td>$($r.Check)</td><td>$($r.Resource)</td><td style='color:$color;font-weight:700'>$icon $($r.Status)</td><td>$($r.Details)</td></tr>"
}
$pass=$($results|Where-Object Status -eq "PASS").Count; $fail=$($results|Where-Object Status -eq "FAIL").Count
$warn=$($results|Where-Object Status -eq "WARN").Count; $total=$results.Count
$html = Get-HtmlTemplate -Title "Full Compliance Assessment" -SubName $subName -Date $date -Rows $rows -Pass $pass -Fail $fail -Warn $warn -Total $total
$html | Out-File "AzureFullAssessment_Report.html" -Encoding UTF8
Write-Host ""; Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " ✅ Full Assessment Complete!" -ForegroundColor Green
Write-Host " 📥 Downloading report automatically..." -ForegroundColor Yellow
Write-Host " Report: AzureFullAssessment_Report.html" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Cyan
download AzureFullAssessment_Report.html
