# ============================================================
#  Azure Network Security Assessment
#  Generates: AzureNetwork_Report.html
#  Run via: irm <raw_github_url>/Network_Audit.ps1 | iex
# ============================================================

function Get-HtmlTemplate {
    param($Title, $SubName, $Date, $Rows, $Pass, $Fail, $Warn, $Total)
    $score = if ($Total -gt 0) { [math]::Round(($Pass / $Total) * 100) } else { 0 }
    $scoreColor = if ($score -ge 80) { "#00c87a" } elseif ($score -ge 60) { "#ffab40" } else { "#ff4d6d" }
    return @"
<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>Azure Assessment - $Title</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;background:#0a0e1a;color:#e8eaf0;min-height:100vh;padding:30px}.container{max-width:1200px;margin:0 auto}.header{background:linear-gradient(135deg,#0078D4,#003f73);border-radius:16px;padding:32px 36px;margin-bottom:28px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}.header h1{font-size:1.7rem;font-weight:800}.header p{font-size:0.85rem;opacity:.75;margin-top:6px}.score-circle{width:90px;height:90px;border-radius:50%;background:conic-gradient($scoreColor ${score}%, rgba(255,255,255,0.1) 0);display:flex;align-items:center;justify-content:center;flex-direction:column;position:relative}.score-inner{width:72px;height:72px;border-radius:50%;background:#0d1a2e;display:flex;align-items:center;justify-content:center;flex-direction:column;position:absolute}.score-num{font-size:1.3rem;font-weight:800;color:$scoreColor}.score-label{font-size:0.6rem;color:#8892a4;text-transform:uppercase;letter-spacing:.05em}.summary-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:16px;margin-bottom:28px}.sum-card{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:18px;text-align:center}.sum-card .num{font-size:2rem;font-weight:800;margin-bottom:4px}.sum-card .lbl{font-size:0.75rem;color:#8892a4;text-transform:uppercase;letter-spacing:.06em}.pass .num{color:#00c87a}.fail .num{color:#ff4d6d}.warn .num{color:#ffab40}.total .num{color:#50e6ff}table{width:100%;border-collapse:collapse;background:rgba(255,255,255,0.03);border-radius:12px;overflow:hidden}th{background:rgba(0,120,212,0.35);padding:12px 16px;text-align:left;font-size:0.78rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#b0c4de}td{padding:11px 16px;font-size:0.85rem;border-bottom:1px solid rgba(255,255,255,0.06);vertical-align:top}tr:last-child td{border-bottom:none}tr:hover td{background:rgba(0,120,212,0.07)}.footer{text-align:center;margin-top:30px;font-size:0.8rem;color:#4a5568;padding:16px}</style></head>
<body><div class='container'>
  <div class='header'><div><h1>☁ Azure $Title</h1><p>Subscription: $SubName &nbsp;|&nbsp; Generated: $Date</p></div><div class='score-circle'><div class='score-inner'><span class='score-num'>${score}%</span><span class='score-label'>Score</span></div></div></div>
  <div class='summary-cards'><div class='sum-card total'><div class='num'>$Total</div><div class='lbl'>Total Checks</div></div><div class='sum-card pass'><div class='num'>$Pass</div><div class='lbl'>Passed</div></div><div class='sum-card fail'><div class='num'>$Fail</div><div class='lbl'>Failed</div></div><div class='sum-card warn'><div class='num'>$Warn</div><div class='lbl'>Warnings</div></div></div>
  <table><thead><tr><th>Category</th><th>Check</th><th>Resource</th><th>Status</th><th>Details</th></tr></thead><tbody>$Rows</tbody></table>
  <div class='footer'>Azure Cloud Assessment Report &nbsp;|&nbsp; Generated by PowerShell Automation</div>
</div></body></html>
"@
}

Write-Host "Connecting to Azure..." -ForegroundColor Cyan
Connect-AzAccount | Out-Null
$results = @()
$sub     = Get-AzSubscription | Select-Object -First 1
$date    = Get-Date -Format "yyyy-MM-dd HH:mm"
$subName = $sub.Name
Write-Host "Running Network checks on: $subName" -ForegroundColor Yellow

# NSG Rules
try {
    $nsgs = Get-AzNetworkSecurityGroup
    foreach ($nsg in $nsgs) {
        $openRules = $nsg.SecurityRules | Where-Object { $_.Access -eq "Allow" -and $_.Direction -eq "Inbound" -and $_.SourceAddressPrefix -in @("*","Internet","0.0.0.0/0") }
        foreach ($rule in $openRules) {
            $riskPort = $rule.DestinationPortRange -in @("22","3389","*","80","8080","443","23","21")
            $results += [PSCustomObject]@{ Category="NSG"; Check="Open Inbound Port $($rule.DestinationPortRange)"; Resource=$nsg.Name; Status=if($riskPort){"FAIL"}else{"WARN"}; Details="Rule: $($rule.Name) — Source: $($rule.SourceAddressPrefix)" }
        }
        if (-not $openRules) { $results += [PSCustomObject]@{ Category="NSG"; Check="No Risky Inbound Rules"; Resource=$nsg.Name; Status="PASS"; Details="No publicly open inbound rules detected" } }
    }
} catch { $results += [PSCustomObject]@{ Category="NSG"; Check="NSG Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# Public IPs
try {
    $pips = Get-AzPublicIpAddress
    foreach ($pip in $pips) {
        $associated = $pip.IpConfiguration -ne $null
        $results += [PSCustomObject]@{ Category="Network"; Check=if($associated){"Public IP In Use"}else{"Orphaned Public IP"}; Resource=$pip.Name; Status=if($associated){"WARN"}else{"FAIL"}; Details="IP: $($pip.IpAddress) — $($pip.PublicIpAllocationMethod)" }
    }
    if (-not $pips) { $results += [PSCustomObject]@{ Category="Network"; Check="Public IPs"; Resource="Subscription"; Status="PASS"; Details="No public IPs found" } }
} catch { $results += [PSCustomObject]@{ Category="Network"; Check="Public IP Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

# VNets & DDoS
try {
    $vnets = Get-AzVirtualNetwork
    foreach ($v in $vnets) {
        $ddos = $v.DdosProtectionPlan -ne $null
        $results += [PSCustomObject]@{ Category="Network"; Check="DDoS Protection"; Resource=$v.Name; Status=if($ddos){"PASS"}else{"WARN"}; Details=if($ddos){"DDoS Standard enabled"}else{"DDoS Standard not enabled"} }
    }
} catch { $results += [PSCustomObject]@{ Category="Network"; Check="VNet/DDoS Scan"; Resource="N/A"; Status="ERROR"; Details=$_.Exception.Message } }

Write-Host "Generating HTML report..." -ForegroundColor Cyan
$rows = ""
foreach ($r in $results) {
    $color = switch ($r.Status) { "PASS"{"#00c87a"} "FAIL"{"#ff4d6d"} "WARN"{"#ffab40"} "INFO"{"#50e6ff"} default{"#8892a4"} }
    $icon  = switch ($r.Status) { "PASS"{"✔"} "FAIL"{"✘"} "WARN"{"⚠"} default{"ℹ"} }
    $rows += "<tr><td>$($r.Category)</td><td>$($r.Check)</td><td>$($r.Resource)</td><td style='color:$color;font-weight:700'>$icon $($r.Status)</td><td>$($r.Details)</td></tr>"
}
$pass=$($results|Where-Object Status -eq "PASS").Count; $fail=$($results|Where-Object Status -eq "FAIL").Count
$warn=$($results|Where-Object Status -eq "WARN").Count; $total=$results.Count
$html = Get-HtmlTemplate -Title "Network Security Audit" -SubName $subName -Date $date -Rows $rows -Pass $pass -Fail $fail -Warn $warn -Total $total
$html | Out-File "AzureNetwork_Report.html" -Encoding UTF8
Write-Host ""; Write-Host "============================================" -ForegroundColor Cyan
Write-Host " ✅ Report Ready: AzureNetwork_Report.html" -ForegroundColor Green
Write-Host ""; Write-Host " DOWNLOAD TO YOUR LAPTOP:" -ForegroundColor Yellow
Write-Host " 1. Click the [ ↑↓ ] icon in Cloud Shell toolbar" -ForegroundColor White
Write-Host " 2. Select 'Download a file'" -ForegroundColor White
Write-Host " 3. Enter: AzureNetwork_Report.html" -ForegroundColor White
Write-Host "============================================" -ForegroundColor Cyan
