# ============================================================
#  Azure Storage Security Assessment
#  Generates: AzureStorage_Report.html
# ============================================================

# ── HTML Template Function ──────────────────────────────────
function Get-HtmlTemplate {
    param($Title, $SubName, $Date, $Rows, $Pass, $Fail, $Warn, $Total)
    $score = if ($Total -gt 0) { [math]::Round(($Pass / $Total) * 100) } else { 0 }
    $scoreColor = if ($score -ge 80) { "#00c87a" } elseif ($score -ge 60) { "#ffab40" } else { "#ff4d6d" }
    
    return @"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title>Azure Assessment - $Title</title>
    <link rel="icon" type="image/png" href="Screenshot_2026-03-10_201227-removebg-preview.png">
    <style>
        *{box-sizing:border-box;margin:0;padding:0}
        body{font-family:'Segoe UI',Arial,sans-serif;background:#0a0e1a;color:#e8eaf0;min-height:100vh;padding:30px}
        .container{max-width:1200px;margin:0 auto}
        .header{background:linear-gradient(135deg,#0078D4,#003f73);border-radius:16px;padding:32px 36px;margin-bottom:28px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}
        .header h1{font-size:1.7rem;font-weight:800}
        .header p{font-size:0.85rem;opacity:.75;margin-top:6px}
        .score-circle{width:90px;height:90px;border-radius:50%;background:conic-gradient($scoreColor ${score}%, rgba(255,255,255,0.1) 0);display:flex;align-items:center;justify-content:center;flex-direction:column;position:relative}
        .score-inner{width:72px;height:72px;border-radius:50%;background:#0d1a2e;display:flex;align-items:center;justify-content:center;flex-direction:column;position:absolute}
        .score-num{font-size:1.3rem;font-weight:800;color:$scoreColor}
        .score-label{font-size:0.6rem;color:#8892a4;text-transform:uppercase;letter-spacing:.05em}
        .summary-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:16px;margin-bottom:28px}
        .sum-card{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:18px;text-align:center}
        .sum-card .num{font-size:2rem;font-weight:800;margin-bottom:4px}
        .sum-card .lbl{font-size:0.75rem;color:#8892a4;text-transform:uppercase;letter-spacing:.06em}
        .pass .num{color:#00c87a} .fail .num{color:#ff4d6d} .warn .num{color:#ffab40} .total .num{color:#50e6ff}
        table{width:100%;border-collapse:collapse;background:rgba(255,255,255,0.03);border-radius:12px;overflow:hidden}
        th{background:rgba(0,120,212,0.35);padding:12px 16px;text-align:left;font-size:0.78rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#b0c4de}
        td{padding:11px 16px;font-size:0.85rem;border-bottom:1px solid rgba(255,255,255,0.06);vertical-align:top}
        tr:last-child td{border-bottom:none}
        tr:hover td{background:rgba(0,120,212,0.07)}
        .footer{text-align:center;margin-top:30px;font-size:0.8rem;color:#4a5568;padding:16px}
    </style>
</head>
<body>
<div class='container'>
    <div class='header'>
        <div><h1>☁ Azure $Title</h1><p>Subscription: $SubName &nbsp;|&nbsp; Generated: $Date</p></div>
        <div class='score-circle'><div class='score-inner'><span class='score-num'>${score}%</span><span class='score-label'>Score</span></div></div>
    </div>
    <div class='summary-cards'>
        <div class='sum-card total'><div class='num'>$Total</div><div class='lbl'>Total Checks</div></div>
        <div class='sum-card pass'><div class='num'>$Pass</div><div class='lbl'>Passed</div></div>
        <div class='sum-card fail'><div class='num'>$Fail</div><div class='lbl'>Failed</div></div>
        <div class='sum-card warn'><div class='num'>$Warn</div><div class='lbl'>Warnings</div></div>
    </div>
    <table>
        <thead><tr><th>Category</th><th>Check</th><th>Resource</th><th>Status</th><th>Details</th></tr></thead>
        <tbody>$Rows</tbody>
    </table>
    <div class='footer'>Azure Cloud Assessment Report &nbsp;|&nbsp; Generated by PowerShell Automation</div>
</div>
</body>
</html>
"@
}

# ── Assessment ──────────────────────────────────────────────
Write-Host "Checking for required Azure modules..." -ForegroundColor Cyan
if (-not (Get-Module -ListAvailable -Name Az.Storage)) {
    Write-Host "Installing Az.Storage module..." -ForegroundColor Yellow
    Install-Module -Name Az.Storage -AllowClobber -Force -Scope CurrentUser
} else {
    # Check if Get-AzStorageAccountSasPolicy exists, if not update
    if (-not (Get-Command Get-AzStorageAccountSasPolicy -ErrorAction SilentlyContinue)) {
        Write-Host "Updating Az.Storage module to support SAS Policy cmdlets..." -ForegroundColor Yellow
        Update-Module -Name Az.Storage -Force -ErrorAction SilentlyContinue
    }
}

Write-Host "Connecting to Azure..." -ForegroundColor Cyan
Connect-AzAccount -ErrorAction SilentlyContinue | Out-Null

$results = @()
$context = Get-AzContext
if (-not $context) { 
    Write-Host " ❌ No context found. Please ensure you are logged in." -ForegroundColor Red
    return 
}
$subName = $context.Subscription.Name
$subId   = $context.Subscription.Id
$date    = (Get-Date).ToUniversalTime().AddHours(5.5).ToString("yyyy-MM-dd HH:mm")

Write-Host "Running Storage checks on: $subName ($subId)" -ForegroundColor Yellow

# Add Context Row
$results += [PSCustomObject]@{ Category="Subscription"; Check="Active Context"; Resource=$subName; Status="PASS"; Details="Successfully identified subscription: $subId" }

try {

$accounts = Get-AzStorageAccount

foreach ($sa in $accounts){

$name = $sa.StorageAccountName
$rg = $sa.ResourceGroupName
$ctx = $sa.Context

# Secure Transfer Required
$results += [PSCustomObject]@{
Category="Storage"
Check="Secure transfer required"
Resource=$name
Status=if($sa.EnableHttpsTrafficOnly){"PASS"}else{"FAIL"}
Details=if($sa.EnableHttpsTrafficOnly){"HTTPS enforced"}else{"HTTP allowed"}
}

# Public Blob Access
$results += [PSCustomObject]@{
Category="Storage"
Check="Public blob access disabled"
Resource=$name
Status=if($sa.AllowBlobPublicAccess){"FAIL"}else{"PASS"}
Details=if($sa.AllowBlobPublicAccess){"Public blob access enabled"}else{"Public access disabled"}
}

# Minimum TLS
$results += [PSCustomObject]@{
Category="Storage"
Check="Minimum TLS version"
Resource=$name
Status=if($sa.MinimumTlsVersion -ge "TLS1_2"){"PASS"}else{"FAIL"}
Details="Configured TLS: $($sa.MinimumTlsVersion)"
}

# Network Rules
$results += [PSCustomObject]@{
Category="Storage"
Check="Storage firewall enabled"
Resource=$name
Status=if($sa.NetworkRuleSet.DefaultAction -eq "Deny"){"PASS"}else{"WARN"}
Details=if($sa.NetworkRuleSet.DefaultAction -eq "Deny"){"Restricted network access"}else{"Public access allowed"}
}

# Blob Encryption
$results += [PSCustomObject]@{
Category="Storage"
Check="Blob service encryption"
Resource=$name
Status=if($sa.Encryption.Services.Blob.Enabled){"PASS"}else{"FAIL"}
Details=if($sa.Encryption.Services.Blob.Enabled){"Blob encryption enabled"}else{"Encryption disabled"}
}

# File Encryption
$results += [PSCustomObject]@{
Category="Storage"
Check="File service encryption"
Resource=$name
Status=if($sa.Encryption.Services.File.Enabled){"PASS"}else{"FAIL"}
Details=if($sa.Encryption.Services.File.Enabled){"File encryption enabled"}else{"Encryption disabled"}
}

# Access Key Rotation
try{
$keys = Get-AzStorageAccountKey -ResourceGroupName $rg -Name $name

$rotationIssue = $false
$details = ""

foreach($key in $keys){
    if($key.CreationTime){
        $age = (Get-Date) - $key.CreationTime
        if($age.Days -gt 90){
            $rotationIssue = $true
        }
        $details += "$($key.KeyName) age: $($age.Days) days; "
    }
}

$status = if($rotationIssue){"FAIL"}else{"PASS"}

$results += [PSCustomObject]@{
Category="Storage"
Check="Storage access key rotation"
Resource=$name
Status=$status
Details=$details
}
}catch{
$results += [PSCustomObject]@{
Category="Storage"
Check="Storage access key rotation"
Resource=$name
Status="WARN"
Details="Unable to verify key rotation"
}
}

# Fetch SAS Policy
$policy = Get-AzStorageAccountSasPolicy -ResourceGroupName $rg -StorageAccountName $name -ErrorAction SilentlyContinue

# SAS Expiry
if($policy -and $policy.SasExpirationPeriod){
    if([timespan]$policy.SasExpirationPeriod -le [timespan]"01:00:00"){
        $status="PASS"
    }
    else{
        $status="FAIL"
    }
    $detail="SAS expiration policy: $($policy.SasExpirationPeriod)"
}
else{
    $status="WARN"
    $detail="No SAS expiration policy configured"
}

$results += [PSCustomObject]@{
Category="Storage"
Check="SAS token expiry"
Resource=$name
Status=$status
Details=$detail
}

# SAS HTTPS
if($policy){
    $httpsOnly = $policy.Protocol -eq "Https"
    $results += [PSCustomObject]@{
    Category="Storage"
    Check="SAS HTTPS enforcement"
    Resource=$name
    Status=if($httpsOnly){"PASS"}else{"FAIL"}
    Details="SAS tokens must allow HTTPS only"
    }
}else{
    $results += [PSCustomObject]@{
    Category="Storage"
    Check="SAS HTTPS enforcement"
    Resource=$name
    Status="WARN"
    Details="Could not read SAS policy or no policy defined."
    }
}

# Blob Containers Public Access
try{

$containers = Get-AzStorageContainer -Context $ctx

foreach($c in $containers){

$results += [PSCustomObject]@{
Category="Storage"
Check="Blob container public access"
Resource="$name / $($c.Name)"
Status=if($c.PublicAccess -eq "Off"){"PASS"}else{"FAIL"}
Details=if($c.PublicAccess -eq "Off"){"Private container"}else{"Public access enabled"}
}

}

}catch{}

# Soft Delete
try{

$blobProp = Get-AzStorageServiceProperty -ServiceType Blob -Context $ctx

$results += [PSCustomObject]@{
Category="Storage"
Check="Blob soft delete"
Resource=$name
Status=if($blobProp.DeleteRetentionPolicy.Enabled){"PASS"}else{"WARN"}
Details=if($blobProp.DeleteRetentionPolicy.Enabled){"Enabled ($($blobProp.DeleteRetentionPolicy.Days) days)"}else{"Soft delete disabled"}
}

}catch{}

}

if(-not $accounts){

$results += [PSCustomObject]@{
Category="Storage"
Check="Storage accounts"
Resource="Subscription"
Status="INFO"
Details="No storage accounts found"
}

}

}catch{

$results += [PSCustomObject]@{
Category="Storage"
Check="Storage scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ── Generate Report ─────────────────────────────────────────
Write-Host "Generating HTML report..." -ForegroundColor Cyan
$rows = ""
foreach ($r in $results) {
    $color = switch ($r.Status) { "PASS"{"#00c87a"} "FAIL"{"#ff4d6d"} "WARN"{"#ffab40"} "INFO"{"#50e6ff"} default{"#8892a4"} }
    $icon  = switch ($r.Status) { "PASS"{"✔"} "FAIL"{"✘"} "WARN"{"⚠"} default{"ℹ"} }
    $rows += "<tr><td>$($r.Category)</td><td>$($r.Check)</td><td>$($r.Resource)</td><td style='color:$color;font-weight:700'>$icon $($r.Status)</td><td>$($r.Details)</td></tr>"
}

$pass = ($results | Where-Object Status -eq "PASS").Count
$fail = ($results | Where-Object Status -eq "FAIL").Count
$warn = ($results | Where-Object Status -eq "WARN").Count
$total = $results.Count

$html = Get-HtmlTemplate -Title "Storage Security Audit" -SubName $subName -Date $date -Rows $rows -Pass $pass -Fail $fail -Warn $warn -Total $total
$html | Out-File "AzureStorage_Report.html" -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " ✅ Report Ready: AzureStorage_Report.html" -ForegroundColor Green
Write-Host " 📥 Downloading automatically..." -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Cyan
download AzureStorage_Report.html