# ============================================================
#  Azure Compute Security Audit (60+ Checks)
#  Generates: AzureCompute_Report.html
#  Run via: irm <raw_github_url>/VM_Audit.ps1 | iex
# ============================================================

function Get-HtmlTemplate {
    param($Title, $SubName, $Date, $Rows, $Pass, $Fail, $Warn, $Total)
    $score = if ($Total -gt 0) { [math]::Round(($Pass / $Total) * 100) } else { 0 }
    $scoreColor = if ($score -ge 80) { "#00c87a" } elseif ($score -ge 60) { "#ffab40" } else { "#ff4d6d" }
    return @"
<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>Azure Assessment - $Title</title><link rel="icon" type="image/png" href="Screenshot_2026-03-10_201227-removebg-preview.png">
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;background:#0a0e1a;color:#e8eaf0;min-height:100vh;padding:30px}.container{max-width:1200px;margin:0 auto}.header{background:linear-gradient(135deg,#0078D4,#003f73);border-radius:16px;padding:32px 36px;margin-bottom:28px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}.header h1{font-size:1.7rem;font-weight:800}.header p{font-size:0.85rem;opacity:.75;margin-top:6px}.score-circle{width:90px;height:90px;border-radius:50%;background:conic-gradient($scoreColor ${score}%, rgba(255,255,255,0.1) 0);display:flex;align-items:center;justify-content:center;flex-direction:column;position:relative}.score-inner{width:72px;height:72px;border-radius:50%;background:#0d1a2e;display:flex;align-items:center;justify-content:center;flex-direction:column;position:absolute}.score-num{font-size:1.3rem;font-weight:800;color:$scoreColor}.score-label{font-size:0.6rem;color:#8892a4;text-transform:uppercase;letter-spacing:.05em}.summary-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:16px;margin-bottom:28px}.sum-card{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:18px;text-align:center}.sum-card .num{font-size:2rem;font-weight:800;margin-bottom:4px}.sum-card .lbl{font-size:0.75rem;color:#8892a4;text-transform:uppercase;letter-spacing:.06em}.pass .num{color:#00c87a}.fail .num{color:#ff4d6d}.warn .num{color:#ffab40}.total .num{color:#50e6ff}table{width:100%;border-collapse:collapse;background:rgba(255,255,255,0.03);border-radius:12px;overflow:hidden}th{background:rgba(0,120,212,0.35);padding:12px 16px;text-align:left;font-size:0.78rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#b0c4de}td{padding:11px 16px;font-size:0.85rem;border-bottom:1px solid rgba(255,255,255,0.06);vertical-align:top}tr:last-child td{border-bottom:none}tr:hover td{background:rgba(0,120,212,0.07)}.footer{text-align:center;margin-top:30px;font-size:0.8rem;color:#4a5568;padding:16px}</style></head>
<body><div class='container'>
  <div class='header'><div><h1>☁ Azure $Title</h1><p>Subscription: $SubName &nbsp;|&nbsp; Generated: $Date</p></div><div class='score-circle'><div class='score-inner'><span class='score-num'>${score}%</span><span class='score-label'>Score</span></div></div></div>
  <div class='summary-cards'><div class='sum-card total'><div class='num'>$Total</div><div class='lbl'>Total Checks</div></div><div class='sum-card pass'><div class='num'>$Pass</div><div class='lbl'>Passed</div></div><div class='sum-card fail'><div class='num'>$Fail</div><div class='lbl'>Failed</div></div><div class='sum-card warn'><div class='num'>$Warn</div><div class='lbl'>Warnings</div></div></div>
  <table><thead><tr><th>Category</th><th>Check</th><th>Resource</th><th>Status</th><th>Details</th></tr></thead><tbody>$Rows</tbody></table>
  <div class='footer'>Azure Cloud Assessment Report &nbsp;|&nbsp; Generated by PowerShell Automation</div>
</div></body></html>
"@
}

Write-Host "Connecting to Azure..." -ForegroundColor Cyan
# In Cloud Shell, Connect-AzAccount is already done but we run it for local compat
Connect-AzAccount -ErrorAction SilentlyContinue | Out-Null
$results = @()
$date    = (Get-Date).ToUniversalTime().AddHours(5.5).ToString("yyyy-MM-dd HH:mm")

# Get Active Subscription context
$context = Get-AzContext
if (-not $context) {
    Write-Host " ❌ No Azure context found. Please ensure you are logged in." -ForegroundColor Red
    return
}
$subName = $context.Subscription.Name
$subId   = $context.Subscription.Id
Write-Host "Running Compute Audit on: $subName ($subId)" -ForegroundColor Yellow

# Add default Context row to ensure report is never 100% empty
$results += [PSCustomObject]@{ Category="Subscription"; Check="Active Context"; Resource=$subName; Status="PASS"; Details="Successfully identified subscription: $subId" }

# ─────────────────────────────────────────────────────────────
# 1. ORPHANED RESOURCES
# ─────────────────────────────────────────────────────────────
Write-Host "[1/7] Orphaned Resources & Global Config..." -ForegroundColor Cyan
try {
    $allDisks = Get-AzDisk -ErrorAction SilentlyContinue
    $unattachedDisks = $allDisks | Where-Object { $_.ManagedBy -eq $null }
    foreach ($disk in $unattachedDisks) {
        $results += [PSCustomObject]@{ Category="Orphaned"; Check="Remove Unattached Disks"; Resource=$disk.Name; Status="FAIL"; Details="Disk is not attached to any VM" }
    }
    if (-not $unattachedDisks) { $results += [PSCustomObject]@{ Category="Orphaned"; Check="Unattached Disks"; Resource="N/A"; Status="INFO"; Details="No unattached disks found" } }
    
    $lbs = Get-AzLoadBalancer -ErrorAction SilentlyContinue
    foreach ($lb in $lbs) {
        $isUsed = $lb.FrontendIpConfigurations.Count -gt 0 -and $lb.BackendAddressPools.Count -gt 0
        if (-not $isUsed) {
            $results += [PSCustomObject]@{ Category="Network"; Check="Unused Load Balancer"; Resource=$lb.Name; Status="FAIL"; Details="Load Balancer is not being used" }
        }
    }
} catch { }

# ─────────────────────────────────────────────────────────────
# 2. VIRTUAL MACHINES & VMSS
# ─────────────────────────────────────────────────────────────
Write-Host "[2/7] Virtual Machines & Scale Sets..." -ForegroundColor Cyan
try {
    $vms = Get-AzVM -ErrorAction SilentlyContinue
    foreach ($vm in $vms) {
        $name = $vm.Name; $rg = $vm.ResourceGroupName
        
        # 1. SSH Auth Type
        if ($vm.StorageProfile.OsDisk.OsType -eq "Linux") {
            try {
                $sshAuth = $vm.OSProfile.LinuxConfiguration.DisablePasswordAuthentication
                $results += [PSCustomObject]@{ Category="VM Security"; Check="SSH Auth Type"; Resource=$name; Status=if($sshAuth){"PASS"}else{"FAIL"}; Details=if($sshAuth){"SSH Keys only"}else{"Password allowed"} }
            } catch {}
        }

        # 2. Disk Encryption
        $enc = Get-AzVMDiskEncryptionStatus -ResourceGroupName $rg -VMName $name -ErrorAction SilentlyContinue
        $results += [PSCustomObject]@{ Category="VM Security"; Check="Boot Disk Encryption"; Resource=$name; Status=if($enc.OsVolumeEncrypted -eq "Encrypted"){"PASS"}else{"FAIL"}; Details="OS Disk: $($enc.OsVolumeEncrypted)" }

        # 3. Managed Identity
        $hasMI = $vm.Identity -ne $null
        $results += [PSCustomObject]@{ Category="VM Security"; Check="Managed Identity"; Resource=$name; Status=if($hasMI){"PASS"}else{"WARN"}; Details=if($hasMI){"Identity: $($vm.Identity.Type)"}else{"No managed identity"} }
    }
    if (-not $vms) { $results += [PSCustomObject]@{ Category="Compute"; Check="Virtual Machines"; Resource="Subscription"; Status="INFO"; Details="No VMs found" } }
} catch { }

# ─────────────────────────────────────────────────────────────
# 3. APP SERVICE
# ─────────────────────────────────────────────────────────────
Write-Host "[3/7] App Services..." -ForegroundColor Cyan
try {
    $webApps = Get-AzWebApp -ErrorAction SilentlyContinue
    foreach ($wa in $webApps) {
        $name = $wa.Name
        $results += [PSCustomObject]@{ Category="App Service"; Check="HTTPS-Only"; Resource=$name; Status=if($wa.HttpsOnly){"PASS"}else{"FAIL"}; Details="Redirect: $($wa.HttpsOnly)" }
        $results += [PSCustomObject]@{ Category="App Service"; Check="TLS Latest Version"; Resource=$name; Status=if($wa.SiteConfig.MinTlsVersion -ge "1.2"){"PASS"}else{"FAIL"}; Details="Min TLS: $($wa.SiteConfig.MinTlsVersion)" }
    }
    if (-not $webApps) { $results += [PSCustomObject]@{ Category="App Service"; Check="App Services"; Resource="N/A"; Status="INFO"; Details="No App Services found" } }
} catch { }

# ─────────────────────────────────────────────────────────────
# 4. AKS (KUBERNETES)
# ─────────────────────────────────────────────────────────────
Write-Host "[4/7] AKS Clusters..." -ForegroundColor Cyan
try {
    $aksClusters = Get-AzAksCluster -ErrorAction SilentlyContinue
    foreach ($aks in $aksClusters) {
        $name = $aks.Name
        $results += [PSCustomObject]@{ Category="AKS"; Check="RBAC Enabled"; Resource=$name; Status=if($aks.EnableRbac){"PASS"}else{"FAIL"}; Details="RBAC: $($aks.EnableRbac)" }
    }
    if (-not $aksClusters) { $results += [PSCustomObject]@{ Category="AKS"; Check="AKS Clusters"; Resource="N/A"; Status="INFO"; Details="No AKS clusters found" } }
} catch { }

# ─────────────────────────────────────────────────────────────
# 5. LOGIC APPS
# ─────────────────────────────────────────────────────────────
Write-Host "[5/7] Logic Apps..." -ForegroundColor Cyan
try {
    $logicApps = Get-AzLogicApp -ErrorAction SilentlyContinue
    if (-not $logicApps) { $results += [PSCustomObject]@{ Category="Logic App"; Check="Logic Apps"; Resource="N/A"; Status="INFO"; Details="No Logic Apps found" } }
    foreach ($la in $logicApps) {
        $results += [PSCustomObject]@{ Category="Logic App"; Check="State"; Resource=$la.Name; Status="INFO"; Details="State: $($la.State)" }
    }
} catch { }

# ─────────────────────────────────────────────────────────────
# 6. FUNCTION APPS
# ─────────────────────────────────────────────────────────────
Write-Host "[6/7] Function Apps..." -ForegroundColor Cyan
try {
    $funcApps = Get-AzFunctionApp -ErrorAction SilentlyContinue
    foreach ($fa in $funcApps) {
        $results += [PSCustomObject]@{ Category="Function App"; Check="HTTPS-Only"; Resource=$fa.Name; Status=if($fa.HttpsOnly){"PASS"}else{"FAIL"}; Details="Redirect: $($fa.HttpsOnly)" }
    }
    if (-not $funcApps) { $results += [PSCustomObject]@{ Category="Function App"; Check="Function Apps"; Resource="N/A"; Status="INFO"; Details="No Function Apps found" } }
} catch { }

# ─────────────────────────────────────────────────────────────
# 7. CONTAINER APPS
# ─────────────────────────────────────────────────────────────
Write-Host "[7/7] Container Apps..." -ForegroundColor Cyan
try {
    $containerApps = Get-AzResource -ResourceType "Microsoft.App/containerApps" -ErrorAction SilentlyContinue
    if (-not $containerApps) { $results += [PSCustomObject]@{ Category="Container App"; Check="Container Apps"; Resource="N/A"; Status="INFO"; Details="No Container Apps found" } }
} catch { }

# ── Finalize Report ───────────────────────────────────────────
Write-Host "Generating HTML report..." -ForegroundColor Cyan
$rows = ""
foreach ($r in $results) {
    $color = switch ($r.Status) { "PASS"{"#00c87a"} "FAIL"{"#ff4d6d"} "WARN"{"#ffab40"} "INFO"{"#50e6ff"} default{"#8892a4"} }
    $icon  = switch ($r.Status) { "PASS"{"✔"} "FAIL"{"✘"} "WARN"{"⚠"} default{"ℹ"} }
    $rows += "<tr><td>$($r.Category)</td><td>$($r.Check)</td><td>$($r.Resource)</td><td style='color:$color;font-weight:700'>$icon $($r.Status)</td><td>$($r.Details)</td></tr>"
}
$pass=$($results|Where-Object Status -eq "PASS").Count; $fail=$($results|Where-Object Status -eq "FAIL").Count
$warn=$($results|Where-Object Status -eq "WARN").Count; $total=$results.Count
$html = Get-HtmlTemplate -Title "Compute & Services Audit" -SubName $subName -Date $date -Rows $rows -Pass $pass -Fail $fail -Warn $warn -Total $total
$html | Out-File "AzureCompute_Report.html" -Encoding UTF8
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " ✅ Compute Audit Complete!" -ForegroundColor Green
Write-Host " Report: AzureCompute_Report.html" -ForegroundColor Green
Write-Host " 📥 Downloading automatically..." -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Cyan
download AzureCompute_Report.html
